apiVersion: v1
kind: Service
metadata:
  name: auth-db
  labels:
    name: postgres
    app: auth
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30003
  selector:
    name: postgres
    app: auth
